### PR TITLE
Handles cases where the first line might not be the line that matches the regex

### LINKED ISSUE #3: Incorrect handling of PDOException
This example of an exception coming directly from a live application - the PDOException has the PDO error first, which causes an error on https://github.com/austinkregel/php-exception-probe/blob/master/src/Stacktrace.php#L140, because the regex doesn't match. 

```
$stack = new Kregel\ExceptionProbe\Stacktrace(); 
$stack->parse(<<<EOF
PDOException: SQLSTATE[22008]: Datetime field overflow: 7 ERROR:  date/time field value out of range: "1967-12-0"
HINT:  Perhaps you need a different "datestyle" setting. in /var/www/releases/20181217174644/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:142
Stack trace:
#0 /var/www/releases/20181217174644/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(142): PDOStatement->execute(NULL)
#1 /var/www/releases/20181217174644/vendor/laravel/framework/src/Illuminate/Database/Connection.php(330): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/releases/20181217174644/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into "Dm...', Array)
EOF
);
```

### PR DESCRIPTION
**Pull request by gms8994**
Closes #3

### CODE REVIEW

File: tests/StacktraceTest.php [hunk 1]
```diff
@@ -96,4 +96,27 @@ public function testWeCanHandleLaravelBasedExceptions()
         $this->assertSame('App\Domain\Service\GitHub->__construct(Object(App\Social))', $firstCodeframe->frame);
         $this->assertCount(0, $firstCodeframe->code);
     }
+
+    public function testWeCanHandlePDOBasedExceptions()
+    {
+        $exceptionString = <<<EOS
```
Comment (austinkregel) [inline tests/StacktraceTest.php]: I'm curious, why you're using `<<<EOS` in place of what I have used elsewhere in the tests. 🤔 

Any chance I could bother you to explain the difference in your opinion 😄

File: src/Stacktrace.php [hunk 2]
```diff
@@ -137,7 +137,12 @@ protected function breakUpTheStacks()
             $newMessage = $newMessage[0];
             preg_match_all(static::REGEX_STACK_MESSAGE, $newMessage, $match);
 
-            $this->message = $match[1][0];
+            foreach ($match as $subMatch) {
```
Comment (austinkregel) [inline src/Stacktrace.php]: I'm not opposed at all to this change, I just worry about things going not-displayed. Do you have any ideas on a way to prevent things from going through the cracks? ☹️

**Review by austinkregel — COMMENTED** [review]
I'm still reviewing these changes, but it looks good so far 😄 
Many thanks 😄

File: tests/StacktraceTest.php (hunk 1 above)
Comment (gms8994) [reply tests/StacktraceTest.php]: Mostly the fact that the exception I was using had both single _and_ double quotes in it, but partly it's easier for me to read. I'm happy to adjust to match your styling if you'd prefer - no complaints whatsoever.

File: src/Stacktrace.php (hunk 2 above)
Comment (gms8994) [reply src/Stacktrace.php]: It is possible, and we could probably refactor that code to something like

```
        $this->message = '';
        
        if (! empty($newMessage)) {
            $newMessage = $newMessage[0];
            preg_match_all(static::REGEX_STACK_MESSAGE, $newMessage, $match);
            
            foreach ($match as $subMatch) {
```

this way, if a message _does_ match, it's handled correctly, and if it doesn't, then `$this->message` falls back to the empty string case.

Comment (austinkregel) [reply src/Stacktrace.php]: So I looked into it some more and for this case, we can actually solve this issue while also maintaining some kind of message. (not defaulting to an empty string).

```php
$this->message = $match[1][0] ?? $newMessage
```

Since the `$match[1][0]` bit doesn't seem to always be there, the `$newMessage` bit should always be a string, and thus should have some good useful information.

I'd like to go with this newer solution using the null coalesce operator for simplicity, if you don't mind 😅.

File: tests/StacktraceTest.php (hunk 1 above)
Comment (austinkregel) [reply tests/StacktraceTest.php]: I would really appreciate it if we could keep the same style 😄

**Review by austinkregel — CHANGES_REQUESTED** [review]

File: tests/StacktraceTest.php (hunk 1 above)
Comment (austinkregel) [reply tests/StacktraceTest.php]: Maybe something like 
```
$exceptionString = "PDOException: SQLSTATE[22008]: Datetime field overflow: 7 ERROR:  date/time field value out of range: \"1967-12-0\"\nHINT:  Perhaps you need a different \"datestyle\" setting. in /home/austinkregel/Sites/lager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:142\nStack trace:\n#0 /home/austinkregel/Sites/lager/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(142): PDOStatement->execute(NULL)\n#1 /home/austinkregel/Sites/lager/vendor/laravel/framework/src/Illuminate/Database/Connection.php(330): Doctrine\DBAL\Driver\PDOStatement->execute()\n#2 /home/austinkregel/Sites/lager/vendor/laravel/framework/src/Illuminate/Database/Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into \"ta...', Array)";
```

Comment (gms8994) [reply tests/StacktraceTest.php]: Fixed in c92215d

File: src/Stacktrace.php (hunk 2 above)
Comment (gms8994) [reply src/Stacktrace.php]: Fixed in c92215d

**Comment by gms8994** [comment]
I never saw your responses, apologies for the delays. I've made changes based on your feedback.

**Review by austinkregel — APPROVED** [review]
